import { controlPlanes, etcds, workers, transformKubesprayNodeToString } from "./_helpers.ts";

const ini = String.raw;

export default ini`
# This inventory is auto-generated by 'make generate'
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
${controlPlanes.map(transformKubesprayNodeToString).join("\n")}

[etcd]
${etcds.map(transformKubesprayNodeToString).join("\n")}

[kube_node]
${workers.map(transformKubesprayNodeToString).join("\n")}
`;